### ISSUE TITLE
Adding a non-static listener?

### ISSUE THREAD

**Issue by RutgerRauws** [igormiktor/arduino-EventManager#11]
Hi,

I am working on a project where I want to split everything up into neat classes. For example:
- A sensor class, which will be polled in the main loop and as soon as some interesting value is read, it will queue a new event
- A networking class, which will setup the networking in the constructor. There will also be a poll method which is constantly checking whether a new packet has arrived and will queue a specific event for a specific package.
- The main 'ino', which will contain the `setup()` and `loop()`

**Note**: I am passing a pointer to the EventManager in the constructor of the sensor and networking class in order to queue new events.

So my loop will contain the `processEvent` call and the polling for specific classes. My problem lays in the setup: when I want to add a new EventListener, I want to add the EventListener of a specific class. However, when compiling I get the following error:
`
Main.cpp: In function ‘void setup()’:
Main.cpp:19:85: error: invalid use of non-static member function
  eventManager.addListener(EventManager::kEventUser0, connectivityManager->listener);
`

This did not make sense to me, as I looked through both the EventManager.cpp and EventManager.h and could not find any definition stating that the second argument of the `addListener` method has to be a static function.

When changing the listener to static, my code works fine. Yet I am of course unable to access my non-static attributes of this class. **Please note that I am not fluent in C++ and my gut says I am doing something wrong when passing a (member?) function pointer.** Or is this not supported?

Amazing library and thanks in advance,
Rutger

**Comment by igormiktor** [comment]
Rutger,

The master branch does not support member function pointers, only ordinary function pointers.  The prototype for addListener() in EventManager.h clearly shows it only takes a function pointer, not member function pointers as Listeners.  It would be a significant change to accept member function pointers and I will not make that change on the master branch.

However, there is good news:  Take a look at the branch called "GenericListeners".  In this branch the code has been modified to accept "function objects" as listeners.  The example code on that branch shows you how it works and you can very easily wrap your member function pointer inside a function object.  This is a more general/flexible solution than a member function pointer and it easily allows you to implement what you want.

Because accepting anything beyond a plain function pointer has non-trivial costs in memory foot print and execution speed, I maintain these two branches separately.  

Take a look at the GenericListeners branch and let me know if you have any questions.

Regards,

Igor

**Comment by RutgerRauws** [comment]
Hello Igor,

This seems to be exactly what I need! I totally missed that there was another branch, I'm sorry.
I have switched to the "GenericListeners" branch and it instantly worked.

Thank you!
Rutger
