### ISSUE TITLE
Passing Int's greater than 32000

### ISSUE THREAD

**Issue by GoodnatureBeacon** [igormiktor/arduino-EventManager#16]
I am using this class with interrupts to record the time that an event happens. I want to pass millis() as the parameter however when I print this out it seems to be treating it as a 16 bit signed integer rather than a 32 - i.e, it becomes -32000 at 32000. 

I'd be willing to believe that I was printing this out incorrectly, but all of the types seem ok. Any help would be great, thanks.

**Comment by igormiktor** [comment]
You see this behavior because the event parameter is of type int, which is 16 bit signed.  You can see this in EventManager.h:

` boolean queueEvent( int eventCode, int eventParam, EventPriority pri = kLowPriority );`

So when you pass a 32 bit value, it is truncated to 16 bits.  It is working "as designed".

Designed this way to save very limited SRAM available on Arduinos because for most uses 16-bit event parameters suffice.  

But obviously 16-bits is not sufficient for your use.  The good news is that changing the code to handle a 32-bit event parameter is straightforward if you want to do that locally.

**Comment by igormiktor** [comment]
Try out branch "GoodnatureBeacon".  That branch introduces a special type for the event parameter called EventParamType.  Look at line 42 of EventManager.h.  You'll see that the default is EventParamType is "int".  Comment that line and uncomment the following line that instead makes the default "long".  Then install this as the Arduino library.

It should now work exactly the way you want it to work (with 32-bit event parameters that will successfully handle values from millis().

Please let me know if this works and I will merge it into the master branch (I'll leave the default as "int" but it is now trivial for you to change to "long" so it works for your application.

**Comment by igormiktor** [comment]
Have you had chance to test this?
