### ISSUE TITLE
delete hook

### ISSUE THREAD

**Issue by r00tkillah** [igormiktor/arduino-EventManager#7]
It would be very nice to optionally specify a callback to delete the resource that is passed in to the event handler.  This would be called after the last event is handled of that type.  It is not possible from a handler function to know if there are other handler functions that will also be called, so it is impossible to know if that function should free the resource.

An alternate pattern would be to add an ability to specify that a handler be called last for a particular event type.

**Comment by igormiktor** [comment]
Event handlers take integers as parameters, so I'm not sure what "resources" you want them to delete.  Do you want to instead pass pointers to objects?  This is running on little AVR processors; creating and deleting objects (and therefore allocating and freeing memory) every time you process an event is not a very practical design in this environment.  So that is probably not what you mean.  Please explain further your intended usage.

**Comment by r00tkillah** [comment]
resources can be arbitrary.  For example, I have a statically allocated array of buffers, where each has handle.  I have two listeners to the event.  After all the handlers are called, then the handle should be released.  However, there is no way to know from the handler function if it is the last one in the chain of handlers for this event.

**Comment by igormiktor** [comment]
Understand what you want, but I'm not going to implement this because (1) this is not a feature I will use when coding on an Arduino and (2) implementing this feature in EventManager will add a cost in both extra storage and cycles for all applications, even those that don't use that feature.  So please go ahead and fork; if you have questions about the code base, I'll be glad to help.  Note that you might be able to achieve what you want (probably at lower memory and cycle cost) by adding a reference count to your resource handles (set the count to 2 when you post the event, handlers each decrement by 1 and release when count reaches 0).
