### ISSUE TITLE
util/atomic.h is missing 

### ISSUE THREAD

**Issue by dkgrieshammer** [igormiktor/arduino-EventManager#8]
Arduino v. 1.6.5 on mac atomic.h is missing; thx for your work, best

**Comment by igormiktor** [comment]
Thanks for bringing this to my attention. I'll revise the code to remove the dependence on atomic.h. But it may take me a week or two to get to it due to other commitments. In the meantime as a work-around, you should be able to copy atomic.h from the avr-gcc distribution and install it manually into the appropriate include directory in the Arduino avr-gcc tree (untested, I'm not running 1.6.5 yet).

**Comment by igormiktor** [comment]
Just removed the dependence on atomic.h from master branch.  Compiles fine for me, but I'm still not using Arduino 1.6.5.  Please test and let me know.
