### ISSUE TITLE
Arduino Due potentially not compatible.

### ISSUE THREAD

**Issue by purefield** [igormiktor/arduino-EventManager#9]
When switching our code from the Arduino Mega to the Due we experience issues using this library.

EventManager.cpp:42:5: error: 'SREG' was not declared in this scope
     SREG = *s;

EventManager.cpp:482:20: error: 'SREG' was not declared in this scope
     sregSave = SREG;

EventManager.cpp:483:13: error: 'cli' was not declared in this scope
         cli();

EventManager.cpp:551:13: error: 'cli' was not declared in this scope
         cli();

EventManager.cpp:572:13: error: 'sei' was not declared in this scope
         sei();

**Comment by igormiktor** [comment]
Thanks for the heads up -- regret I don't have a Due to test with.

Can you tell me what the equivalents are for the Due to:

(1) save current status 
(2) turn off interrupts
(3) turn on interrupts
(4) what's the conditional compilation check for the Due

With that I should be able to add conditional code to handle the Due if you would be willing to test.

**Comment by purefield** [comment]
You can just import the due board into the IDE and simulate it. Then you can compile the code. 
We just switched from the mega to the due for it's increased interrupt support.

The reference documentation (as you likely already know) is: 
https://www.arduino.cc/en/Reference/HomePage
https://www.arduino.cc/en/Reference/Interrupts

(1) no idea
(2) noInterrupts();
(3) interrupts();
(4) no idea

**Comment by igormiktor** [comment]
I need lower level primitives (e.g., sei and cli equivalents instead of interrupts() and nointerrupts()). I'll have to dig some and go through some of the Due library source code to figure it out (the reference documentation is not helpful for this kind of stuff).  

I'm locked into an older (non-Due) IDE version (long story), so I can't readily simulate the Due. When I figure out the code, I'll ask you to test.

**Comment by igormiktor** [comment]
I've created a branch called "sam" that is compatible with Due.  I would be very grateful if you would check it out and test this code on your Due.  

Please confirm that it works, and I will merge the changes into the master branch.

Thanks for your help in improving the code.

**Comment by igormiktor** [comment]
And to document answers to my questions "for the record":
1. On a Due, get the current interrupt state:   (__get_PRIMASK() == 0)
2. On a Due, turn off global interrupts:   __disable_irq()
3. On a Due, turn on global interrupts:   __enable_irq()
4. Conditional compilation check for Due (generic):   #if defined( SAM )

**Comment by purefield** [comment]
Awesome, will test.

**Comment by igormiktor** [comment]
Any feedback?  Is it good to go?

**Comment by purefield** [comment]
We switched back to the mega for the time being. Will however test your
changes as soon as we have the chance.

2016-01-27 21:44 GMT-06:00 Igor Mikolic-Torreira notifications@github.com:

**Comment by igormiktor** [comment]
Merged changes (although in somewhat different form)
